server:
   port: 1002
spring:
   application:
      name: training-service
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-8vb5020242t0c8c43o.mysql.zhangbei.rds.aliyuncs.com:3306/fsd?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false&createDatabaseIfNotExist=true
      username: ENC(xCLkxbh9Z1up2aO+TDNVGg==)
      password: ENC(KKSdRDvWvAGy+yurps9rnnO1RxyVc6wi)
   jpa:
      show-sql: true
      generate-ddl: false
      open-in-view: false
      hibernate:
          ddl-auto: none
      properties:
          hibernate:
              enable_lazy_load_no_trans: true
              format_sql : true
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl: 
         defaultZone: http://localhost:8761/eureka/
   instance:
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2
      
ribbon:
   eureka:
      enabled: false

      
logging:
    level:
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        
jasypt: 
    encryptor: 
        password: fsd